### ISSUE TITLE
How to setup a Region Midt PC for development

### ISSUE THREAD

**Issue by benjaminjohansen** [steno-aarhus/research#63]
Give a brief description on how to setup a Region Midt PC for development.

This includes:
- Avanceret bruger (admin rights) + non-standard PC
- What software to get installed by the region (MS office (licence and local install), teams/pexip, VPN, Cisco Proximity, 
- Recommended software installed by the researcher
- How to setup printing

@Aastedet and I have managed to get an almost working Regional laptop. Let's get it documented!

**Comment by Aastedet** [comment]
@benjaminjohansen YES! I've added a branch to flesh out the contents. I've put the guide in the [Onboarding/IT Basics page](https://github.com/steno-aarhus/research/blob/regional-laptop-setup/onboarding/it-basics/index.md).

Feel free to edit and rearrange. And definitely add a guide on printing (I need to print something 😄)
Maybe the old guide to Citrix can be removed if we decide to recommend using the local setup rather than Citrix from now on? @lwjohnst86

**Comment by lwjohnst86** [comment]
That's fabulous you two!! :muscle: Submit a PR and I'll review it :raised_hands:

**Comment by Aastedet** [comment]
I think I've added the basic necessities and gone over the most common quirks. I haven't added printing, but the current content is enough for merging to main, I think.

Before merging the PR, please check if the direct links to the ServicePortal website on steps 1-4 are valid for other RM users (can you check that @benjaminjohansen ? - I don't think @lwjohnst86 has an RM login on hand). Also, feel free to edit text for clarity if needed.

**Comment by lwjohnst86** [comment]
I do have an RM account! I'll check it early next week 🤩

**Comment by Aastedet** [comment]
Awesome. I added a section on printer setup as well.
